### ISSUE TITLE
ignore_paths is not ignoring top level paths

### ISSUE THREAD

**Issue by justin808** [YorickPeterse/ruby-lint#144]
Rails 4.2 app, using ruby-2.1.5. I'm running ruby-lint like:

    ruby-lint .

My config file is: 

```yml
---
presenter: syntastic

directories:
  - app
  - config
  - spec

ignore_paths:
  - client
  - node_modules
```

The problem I'm seeing is that the `ignore_paths` option is ignored.
